# Use the micromamba image as base
FROM docker.io/mambaorg/micromamba:bookworm-slim

# Set environment variables
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV ENV_NAME="itt"
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"
ARG MAMBA_USER=mambauser
ARG MAMBA_USER_ID=57439
ARG MAMBA_USER_GID=57439
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_USER_ID=$MAMBA_USER_ID
ENV MAMBA_USER_GID=$MAMBA_USER_GID
ENV NUMBA_DISABLE_CACHING=1

# Switch to root to install system packages
USER root

#RUN chown -R $MAMBA_USER:$MAMBA_USER /opt/conda/envs/itt/lib/python3.9/site-packages

# Install system packages including basic shell
RUN apt-get update && apt-get install -y --no-install-recommends \
    unzip \
    curl \
    vim \
    bash \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch back to the mambauser
USER $MAMBA_USER

ENV NUMBA_CACHE_DIR=/home/$MAMBA_USER/.numba_cache
RUN mkdir -p $NUMBA_CACHE_DIR && \
    chown -R $MAMBA_USER:$MAMBA_USER $NUMBA_CACHE_DIR

# Copy the environment.yml file into the container
COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml ./

# Create the environment specified in environment.yml without overwriting base environment
RUN micromamba create -n $ENV_NAME -f environment.yml && \
    micromamba install -y -n $ENV_NAME -c conda-forge \
    dask \
    coiled \
    boto3 \
    jupyterlab \
    jupyterhub \
    && micromamba clean --all --yes

# Set the PATH to include the new environment
ENV PATH /opt/conda/envs/$ENV_NAME/bin:$PATH

# Make sure the entrypoint script uses bash
#RUN echo '#!/bin/bash' > /opt/conda/entrypoint.sh && \
#    echo 'micromamba activate $ENV_NAME' >> /opt/conda/entrypoint.sh && \
#    echo 'exec "$@"' >> /opt/conda/entrypoint.sh && \
#    chmod +x /opt/conda/entrypoint.sh

# Set the entrypoint
#ENTRYPOINT ["/opt/conda/entrypoint.sh"]
#CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
# Use micromamba run in the CMD
CMD ["micromamba", "run", "-n", "itt", "jupyterhub-singleuser"]

