#!/usr/bin/env python3
"""
JSON Metadata Validation and Sanity Check Framework
For NOAA CDR Precipitation Dataset JSON references generated by VirtualiZarr
"""

import json
import logging
import warnings
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
from datetime import datetime
import tempfile
import os

import xarray as xr
import numpy as np
from virtualizarr import open_virtual_dataset

# Suppress warnings
warnings.filterwarnings("ignore", category=UserWarning)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)


class JSONValidationFramework:
    """Framework for validating VirtualiZarr-generated JSON reference files"""
    
    def __init__(self, output_dir: str = "."):
        """
        Initialize validation framework
        
        Args:
            output_dir: Directory containing JSON files to validate
        """
        self.output_dir = Path(output_dir)
        self.validation_results = {}
        
    def load_json_reference(self, json_path: Path) -> Optional[Dict[str, Any]]:
        """
        Load and parse JSON reference file
        
        Args:
            json_path: Path to JSON reference file
            
        Returns:
            Parsed JSON dictionary or None if failed
        """
        try:
            with open(json_path, 'r') as f:
                refs_dict = json.load(f)
            return refs_dict
        except Exception as e:
            logger.error(f"Failed to load JSON file {json_path}: {e}")
            return None
    
    def validate_json_structure(self, refs_dict: Dict[str, Any], filename: str) -> Dict[str, Any]:
        """
        Validate basic Kerchunk JSON structure
        
        Args:
            refs_dict: Loaded JSON reference dictionary
            filename: Name of the JSON file
            
        Returns:
            Validation results dictionary
        """
        validation = {
            'filename': filename,
            'structure_valid': True,
            'issues': [],
            'metadata': {}
        }
        
        # Check for required top-level keys
        required_keys = ['refs', 'version']
        for key in required_keys:
            if key not in refs_dict:
                validation['structure_valid'] = False
                validation['issues'].append(f"Missing required key: {key}")
        
        # Validate refs structure
        if 'refs' in refs_dict:
            refs = refs_dict['refs']
            if not isinstance(refs, dict):
                validation['structure_valid'] = False
                validation['issues'].append("'refs' is not a dictionary")
            else:
                # Check for .zattrs (global attributes)
                if '.zattrs' not in refs:
                    validation['issues'].append("Warning: No global attributes (.zattrs) found")
                
                # Check for .zgroup
                if '.zgroup' not in refs:
                    validation['issues'].append("Warning: No .zgroup found")
                
                # Count variables and chunks
                variables = [key for key in refs.keys() if '/' in key and not key.endswith('.zattrs')]
                chunks = [key for key in refs.keys() if key.count('/') >= 2]
                
                validation['metadata'] = {
                    'total_refs': len(refs),
                    'variables_count': len(set([var.split('/')[0] for var in variables])),
                    'chunk_count': len(chunks),
                    'has_global_attrs': '.zattrs' in refs,
                    'has_group_info': '.zgroup' in refs
                }
        
        return validation
    
    def test_data_access(self, json_path: Path) -> Dict[str, Any]:
        """
        Test data access through JSON reference using xarray
        
        Args:
            json_path: Path to JSON reference file
            
        Returns:
            Data access test results
        """
        test_results = {
            'filename': json_path.name,
            'data_access_successful': False,
            'dataset_info': {},
            'issues': [],
            'performance_metrics': {}
        }
        
        try:
            start_time = datetime.now()
            
            # Create temporary file for xarray to read
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as tmp_file:
                # Copy JSON content to temp file
                with open(json_path, 'r') as f:
                    json_content = f.read()
                tmp_file.write(json_content)
                tmp_file_path = tmp_file.name
            
            try:
                # Try to open with xarray using the reference
                ds = xr.open_dataset(tmp_file_path, engine='kerchunk')
                
                load_time = (datetime.now() - start_time).total_seconds()
                
                # Extract basic dataset information
                test_results['dataset_info'] = {
                    'dimensions': dict(ds.dims),
                    'data_variables': list(ds.data_vars.keys()),
                    'coordinates': list(ds.coords.keys()),
                    'attributes_count': len(ds.attrs),
                    'total_size_bytes': ds.nbytes if hasattr(ds, 'nbytes') else 'unknown'
                }
                
                # Test basic operations
                try:
                    # Test coordinate access
                    coord_test = {}
                    for coord in ds.coords:
                        try:
                            coord_data = ds[coord]
                            coord_test[coord] = {
                                'shape': coord_data.shape,
                                'dtype': str(coord_data.dtype),
                                'has_data': coord_data.size > 0
                            }
                        except Exception as e:
                            coord_test[coord] = {'error': str(e)}
                    
                    test_results['coordinate_access'] = coord_test
                    
                    # Test variable metadata access
                    var_test = {}
                    for var in list(ds.data_vars.keys())[:3]:  # Test first 3 variables
                        try:
                            var_data = ds[var]
                            var_test[var] = {
                                'shape': var_data.shape,
                                'dtype': str(var_data.dtype),
                                'chunks': str(var_data.chunks) if hasattr(var_data, 'chunks') else 'no chunks',
                                'attributes_count': len(var_data.attrs)
                            }
                        except Exception as e:
                            var_test[var] = {'error': str(e)}
                    
                    test_results['variable_access'] = var_test
                    
                    test_results['data_access_successful'] = True
                    
                except Exception as access_error:
                    test_results['issues'].append(f"Data access error: {access_error}")
                
                test_results['performance_metrics'] = {
                    'load_time_seconds': load_time,
                    'memory_efficient': True  # Kerchunk should be memory efficient
                }
                
                # Close dataset
                ds.close()
                
            finally:
                # Clean up temp file
                try:
                    os.unlink(tmp_file_path)
                except:
                    pass
                
        except Exception as e:
            test_results['issues'].append(f"Failed to open dataset: {e}")
        
        return test_results
    
    def compare_with_original(self, json_path: Path, original_nc_url: str) -> Dict[str, Any]:
        """
        Compare JSON reference with original NetCDF file (if accessible)
        
        Args:
            json_path: Path to JSON reference file
            original_nc_url: URL to original NetCDF file
            
        Returns:
            Comparison results
        """
        comparison = {
            'filename': json_path.name,
            'original_url': original_nc_url,
            'comparison_successful': False,
            'metadata_match': {},
            'issues': []
        }
        
        try:
            # Load JSON reference
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as tmp_file:
                with open(json_path, 'r') as f:
                    json_content = f.read()
                tmp_file.write(json_content)
                tmp_file_path = tmp_file.name
            
            try:
                # Open both datasets
                ds_json = xr.open_dataset(tmp_file_path, engine='kerchunk')
                ds_original = xr.open_dataset(original_nc_url)
                
                # Compare dimensions
                dims_match = ds_json.dims == ds_original.dims
                comparison['metadata_match']['dimensions'] = {
                    'match': dims_match,
                    'json_dims': dict(ds_json.dims),
                    'original_dims': dict(ds_original.dims)
                }
                
                # Compare variables
                json_vars = set(ds_json.data_vars.keys())
                original_vars = set(ds_original.data_vars.keys())
                vars_match = json_vars == original_vars
                
                comparison['metadata_match']['variables'] = {
                    'match': vars_match,
                    'json_vars': list(json_vars),
                    'original_vars': list(original_vars),
                    'missing_in_json': list(original_vars - json_vars),
                    'extra_in_json': list(json_vars - original_vars)
                }
                
                # Compare coordinates
                json_coords = set(ds_json.coords.keys())
                original_coords = set(ds_original.coords.keys())
                coords_match = json_coords == original_coords
                
                comparison['metadata_match']['coordinates'] = {
                    'match': coords_match,
                    'json_coords': list(json_coords),
                    'original_coords': list(original_coords)
                }
                
                # Compare global attributes
                attrs_match = ds_json.attrs == ds_original.attrs
                comparison['metadata_match']['global_attributes'] = {
                    'match': attrs_match,
                    'json_attrs_count': len(ds_json.attrs),
                    'original_attrs_count': len(ds_original.attrs)
                }
                
                comparison['comparison_successful'] = True
                
                # Overall match assessment
                overall_match = dims_match and vars_match and coords_match
                comparison['overall_metadata_match'] = overall_match
                
                # Close datasets
                ds_json.close()
                ds_original.close()
                
            finally:
                os.unlink(tmp_file_path)
                
        except Exception as e:
            comparison['issues'].append(f"Comparison failed: {e}")
        
        return comparison
    
    def run_performance_benchmarks(self, json_paths: List[Path]) -> Dict[str, Any]:
        """
        Run performance benchmarks on JSON references
        
        Args:
            json_paths: List of JSON reference file paths
            
        Returns:
            Performance benchmark results
        """
        benchmarks = {
            'test_timestamp': datetime.now().isoformat(),
            'total_files_tested': len(json_paths),
            'file_size_analysis': {},
            'load_time_analysis': {},
            'memory_efficiency': {},
            'summary_stats': {}
        }
        
        file_sizes = []
        load_times = []
        successful_loads = 0
        
        for json_path in json_paths:
            try:
                # File size analysis
                file_size_mb = json_path.stat().st_size / 1024 / 1024
                file_sizes.append(file_size_mb)
                
                # Load time test
                start_time = datetime.now()
                refs_dict = self.load_json_reference(json_path)
                load_time = (datetime.now() - start_time).total_seconds()
                
                if refs_dict:
                    load_times.append(load_time)
                    successful_loads += 1
                
            except Exception as e:
                logger.warning(f"Benchmark test failed for {json_path}: {e}")
                continue
        
        # Calculate statistics
        if file_sizes:
            benchmarks['file_size_analysis'] = {
                'min_size_mb': min(file_sizes),
                'max_size_mb': max(file_sizes),
                'avg_size_mb': sum(file_sizes) / len(file_sizes),
                'total_size_mb': sum(file_sizes)
            }
        
        if load_times:
            benchmarks['load_time_analysis'] = {
                'min_load_time_s': min(load_times),
                'max_load_time_s': max(load_times),
                'avg_load_time_s': sum(load_times) / len(load_times)
            }
        
        benchmarks['summary_stats'] = {
            'successful_loads': successful_loads,
            'failed_loads': len(json_paths) - successful_loads,
            'success_rate': f"{successful_loads/len(json_paths)*100:.1f}%" if json_paths else "0%"
        }
        
        return benchmarks
    
    def validate_dataset_directory(self, dataset_dir: Path, original_urls: Optional[List[str]] = None) -> Dict[str, Any]:
        """
        Validate all JSON files in a dataset directory
        
        Args:
            dataset_dir: Directory containing JSON reference files
            original_urls: Optional list of original NetCDF URLs for comparison
            
        Returns:
            Complete validation results for the dataset
        """
        logger.info(f"Validating JSON files in directory: {dataset_dir}")
        
        # Find all JSON files (exclude summary files)
        json_files = [f for f in dataset_dir.glob("*.json") 
                     if not f.name.endswith('_summary.json') 
                     and not f.name.endswith('_validation_results.json')]
        
        if not json_files:
            logger.warning(f"No JSON files found in {dataset_dir}")
            return {'error': 'No JSON files found'}
        
        logger.info(f"Found {len(json_files)} JSON files to validate")
        
        validation_results = {
            'validation_info': {
                'dataset_directory': str(dataset_dir),
                'total_json_files': len(json_files),
                'validation_timestamp': datetime.now().isoformat()
            },
            'individual_file_results': [],
            'summary_statistics': {},
            'performance_benchmarks': {},
            'recommendations': []
        }
        
        # Validate each file
        structure_valid_count = 0
        data_access_count = 0
        
        for i, json_path in enumerate(json_files, 1):
            logger.info(f"Validating file {i}/{len(json_files)}: {json_path.name}")
            
            file_results = {
                'filename': json_path.name,
                'file_path': str(json_path)
            }
            
            # Load JSON
            refs_dict = self.load_json_reference(json_path)
            if not refs_dict:
                file_results['validation_failed'] = True
                file_results['error'] = 'Failed to load JSON file'
                validation_results['individual_file_results'].append(file_results)
                continue
            
            # Structure validation
            structure_result = self.validate_json_structure(refs_dict, json_path.name)
            file_results['structure_validation'] = structure_result
            if structure_result['structure_valid']:
                structure_valid_count += 1
            
            # Data access test
            access_result = self.test_data_access(json_path)
            file_results['data_access_test'] = access_result
            if access_result['data_access_successful']:
                data_access_count += 1
            
            # Original comparison (if URL provided)
            if original_urls and i <= len(original_urls):
                comparison_result = self.compare_with_original(json_path, original_urls[i-1])
                file_results['original_comparison'] = comparison_result
            
            validation_results['individual_file_results'].append(file_results)
        
        # Summary statistics
        validation_results['summary_statistics'] = {
            'structure_valid_files': structure_valid_count,
            'structure_valid_rate': f"{structure_valid_count/len(json_files)*100:.1f}%",
            'data_access_successful': data_access_count,
            'data_access_rate': f"{data_access_count/len(json_files)*100:.1f}%",
            'overall_success_rate': f"{min(structure_valid_count, data_access_count)/len(json_files)*100:.1f}%"
        }
        
        # Performance benchmarks
        validation_results['performance_benchmarks'] = self.run_performance_benchmarks(json_files)
        
        # Generate recommendations
        recommendations = []
        
        if structure_valid_count < len(json_files):
            recommendations.append(f"Fix {len(json_files) - structure_valid_count} files with invalid JSON structure")
        
        if data_access_count < len(json_files):
            recommendations.append(f"Debug {len(json_files) - data_access_count} files with data access issues")
        
        if structure_valid_count == len(json_files) and data_access_count == len(json_files):
            recommendations.append("All JSON files passed validation - ready for production use")
        
        validation_results['recommendations'] = recommendations
        
        # Save validation results
        results_filename = f"{dataset_dir.name}_comprehensive_validation_results.json"
        results_path = dataset_dir / results_filename
        
        with open(results_path, 'w') as f:
            json.dump(validation_results, f, indent=2)
        
        logger.info(f"Validation complete: {data_access_count}/{len(json_files)} files fully functional")
        logger.info(f"Comprehensive validation results saved: {results_path}")
        
        return validation_results


def main():
    """CLI for validation framework"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Validate VirtualiZarr-generated JSON reference files",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        'dataset_directory',
        help='Directory containing JSON reference files to validate'
    )
    
    parser.add_argument(
        '--verbose',
        '-v',
        action='store_true',
        help='Enable verbose logging'
    )
    
    args = parser.parse_args()
    
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    # Run validation
    framework = JSONValidationFramework()
    dataset_dir = Path(args.dataset_directory)
    
    if not dataset_dir.exists():
        logger.error(f"Directory not found: {dataset_dir}")
        exit(1)
    
    results = framework.validate_dataset_directory(dataset_dir)
    
    if 'error' in results:
        logger.error(f"Validation failed: {results['error']}")
        exit(1)
    
    # Print summary
    stats = results['summary_statistics']
    logger.info(f"\\nVALIDATION SUMMARY")
    logger.info(f"Structure validation: {stats['structure_valid_rate']}")
    logger.info(f"Data access: {stats['data_access_rate']}")
    logger.info(f"Overall success: {stats['overall_success_rate']}")
    
    recommendations = results['recommendations']
    if recommendations:
        logger.info(f"\\nRECOMMENDATIONS:")
        for rec in recommendations:
            logger.info(f"- {rec}")
    
    # Exit code based on results
    overall_rate = float(stats['overall_success_rate'].rstrip('%'))
    if overall_rate >= 90:
        exit(0)  # Success
    elif overall_rate >= 70:
        exit(1)  # Partial success
    else:
        exit(2)  # Mostly failed


if __name__ == "__main__":
    main()